// Code generated by goctl. DO NOT EDIT.
package types

type GetUserRequest struct {
	UserId string `json:"userId"`
}

type GetUserResponse struct {
	Name string `json:"name"`
}

type JwtTokenRequest struct {
}

type JwtTokenResponse struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"` // 建议客户端刷新token的绝对时间
}

type AgentListReq struct {
	Name string `form:"name"`
}

type AgentListResp struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type UserByIdResp struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type UserListResp struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type UsertByIdReq struct {
	Id int `form:"id" validate:"gte=1" label:"用户ID"`
}

type UsertListReq struct {
}
